### ISSUE TITLE
Titan' requirement

### ISSUE THREAD

**Issue by LetItRain** [titan-data/titan#130]
My team is doing a technical survey of database versioning. There are some requirements that titan already provides. Could you help me confirm which ones have been achieved and which ones will be realized in the future. thank you very much.

> 1. End users (developer etc.) manage source, time and version with self-service
> • Self-service and branching, bookmarking, refreshing, resetting, rolling back, and integration within minutes.
> • Users can manage data by self-service on the interface with high operability according to authority and role.
>  
> 2. Interface for managing governance, provisioning and allocation
> • Provides interfaces for IT operations such as IT resource (DB / storage) provisioning and allocation management.
> • Provision data across on-premises, data center and cloud environments.
> 
> 3. Ensuring data privacy and security for compliance and internal control purposes
> • Single data vendor provides automatic data masking function required for compliance (PCI etc.)
> • Protect high-risk copy data generated from production.
> 
> 4. Simplify the data change management process
> • Bookmarks can be easily bookmarked according to various events such as batch data entry and core business (eg, quarterly settlement) before and after the release of the production system
> • Set policies for auditing and financial settlement and automatically maintain and manage change records (audit trail)
> • Specify any time (minimum seconds) and SCN to roll back data in minutes. Achieving high-grain PIT (Point-in-time)
> 
> 5. Providing a ready-to-use IT environment
> • Deliver reliable environments 100 times faster
> • Deliver the data group (application binary file, DB file, database) required for the application to the new environment
> 
> 6. Simplify integration of multiple applications
> • Provisioning and refreshing all linked application databases on the same time axis
> • The integrated test environment can be reset and branched instantaneously and repeatedly on the same time axis (= the number of tests that can be performed within the period increases).
> • Simultaneously create multiple test tasks by creating an environment where multiple systems are integrated instantaneously and repeatedly
> 
> 7. Efficient application integration testing
> • Supports application environments that require provisioning of multiple databases on any time axis
> 
> 8. BI analysis without constraints such as time and batch window
> • Offload batch job work by creating a near real-time environment. Reduce production environment load and eliminate batch window restrictions
> • Data processing and report generation using BI tools from a near real-time synchronized environment
> 
> 9. Create an environment that is easy to expand on demand
> • Easy to backup and restore development environment, or create a dedicated report output environment
> 
> 10. Branch and share a concurrent development / test / verification environment
> • Create unlimited virtual environments for parallel development
> • Easily bookmark the data environment under test and share with developers responsible for bug fixes
> 
> 11. Effective use of existing servers, storage and infrastructure
> • Hardware independent
> • Improve the usage rate of existing IT systems 10 times (10 spaces are managed in one space)
> 
> 12. Cloud support: Streamline data migration to the cloud (supports AWS, vCloud Air, Azure, etc.) 
> • Avoid hardware or private cloud lock-in
> • Automate 50% of cloud migration
> • Increase bandwidth utilization by 10 times
> • Automatic conversion from UNIX to LINUX
> 
> 13. Convert UNIX data to LINUX data
> • Automatic conversion from UNIX to LINUX
> 
> 14. High performance in multiple environments
> • Realizes parallel environment and high performance by virtualizing data blocks in memory
> 
> 15. Integrated log management, transaction consistency management
> • High granularity (in seconds) and RPO within minutes
> • Supports Oracle, SQL Server, PostgreSQL, Sybase
> 
> 16. Reduce storage costs and backups
> • Improved storage utilization

**Comment by eschrock** [comment]
Hi LetItRain -

Thanks for the interest in Titan! This looks like set of requirements for a full-blown enterprise data mangement platform, something very different from Titan's design focus. We're a brand-new open source tool focused on providing a better developer experience around managing data. While there is some overlap, we have no intention of providing things like automated data ingestion, integrated masking, translaction-level change management, integrated resource management, etc. I'd suggest looking at something like Delphix. I do believe that we can integrate with those types of platforms, and provide a unified developer experience whether you're working with local test data or data provided through such a platform. But right now our focus is on crafting the core workflows and validating with developers and testers in the market. Enterprise capabilities and integrations are not on our roadmap until we prove out that product fit.

Hope that helps! Feel free to jump on the Titan slack workspace if you want to ask more detailed questions interactively.

**Comment by Shawn-Yuan-byte** [comment]
> Hi LetItRain -
> 
> Thanks for the interest in Titan! This looks like set of requirements for a full-blown enterprise data mangement platform, something very different from Titan's design focus. We're a brand-new open source tool focused on providing a better developer experience around managing data. While there is some overlap, we have no intention of providing things like automated data ingestion, integrated masking, translaction-level change management, integrated resource management, etc. I'd suggest looking at something like Delphix. I do believe that we can integrate with those types of platforms, and provide a unified developer experience whether you're working with local test data or data provided through such a platform. But right now our focus is on crafting the core workflows and validating with developers and testers in the market. Enterprise capabilities and integrations are not on our roadmap until we prove out that product fit.
> 
> Hope that helps! Feel free to jump on the Titan slack workspace if you want to ask more detailed questions interactively.

Can you specifically reply to 1-16, which function can be implemented with titan?
