### ISSUE TITLE
What advantages does titan have compared to flyway?

### ISSUE THREAD

**Issue by Shawn-Yuan-byte** [titan-data/titan#140]
We are evaluating Flyway and Titan. We still can't decide which tool to use for data management. What advantages or disadvantages do you think titan has over flyway？

**Comment by mcred** [comment]
Flyway is a tool for database schema migration. From [wikipedia](https://en.wikipedia.org/wiki/Flyway_(software)), "Flyway is based around seven basic commands: Migrate, Clean, Info, Validate, Undo, Baseline, and Repair."

Titan is for managing data states in containerized databases. It allows you to commit, clone, checkout, push and pull different data states to local and remote repositories (like git). 

Neither tool is a replacement for the other, they do different things. They would work well together, though. With a schema migration tool (Flyway, Liquibase) and titan, you would be able to test your codified schema changes against different data states. If during that testing you discovered a defect, you could commit that state with titan, share it with a developer to fix the defect, and checkout a known working state to fix the bad migration. One is dealing with the schema and one is dealing with the underlying data in the tables.

**Comment by Shawn-Yuan-byte** [comment]
Thank you for your reply
