### ISSUE TITLE
Download link is broken on titan-data.io/download

### ISSUE THREAD

**Issue by ericwooley** [titan-data/titan#210]
I just thought you should know.

The link right now points to: https://github.com/titan-data/titan/releases/download/0.5.0/titan-cli-0.5.0-linux_amd64.tar
It should point to: https://github.com/titan-data/titan/releases/download/0.5.0/titan-cli-0.5.0-linux_amd64.zip

I'm guessing you update these manually, I use this JS snippet for getting the latest download link. Feel free to steal / adapt it for your site.
```js
<script>
function replaceLink(platform, url) {
 document.getElementById('download-'+platform).querySelector('a').setAttribute('href', url)
}

fetch('https://api.github.com/repos/tengable/tengable-releases/releases/latest')
.then(res => res.json())
.then((response) => {
    const assetUrls = response.assets.map(asset => asset.browser_download_url)
    linuxUrl = assetUrls.find(url => url.indexOf('AppImage') !== -1)
    replaceLink('linux', linuxUrl)
    osxUrl = assetUrls.find(url => url.indexOf('dmg') !== -1)
    replaceLink('osx', osxUrl)
    winUrl = assetUrls.find(url => url.indexOf('msi') !== -1)
    replaceLink('windows', winUrl)
})
</script> 
```

**Comment by mcred** [comment]
Thanks for the heads up! It should be a tar release and not a zip release. It's been updated.
