### ISSUE TITLE
The logger give some advice, but I don't understand it.

### ISSUE THREAD

**Issue by cirdeCyL** [titan-data/titan#274]
## Expected Behavior

SO I was trying out Titan with my own dataset. 
Essentially I preprocessed my files to have the same column name. Labelling my CDR3 and Epitopes and further transform the epitopes in smiles.
So now running the semifrozen training, I expected the to have no problems.
## Actual Behavior

Instead I got this prompted.
`Here are the problems:
Provided arg add_start_and_stop:True does not match the smiles_language value: False NOTE: smiles_language value takes preference!!
Provided arg padding:True does not match the smiles_language value: False NOTE: smiles_language value takes preference!!
Provided arg padding_length:500 does not match the smiles_language value: None NOTE: smiles_language value takes preference!!
To get rid of this, adapt the smiles_language *offline*, feed itready for intended usage, and adapt the constructor args to be identical with their equivalents in the language object
Since you provided a smiles_language, the following parameters to this class will be ignored: canonical, augment, kekulize, all_bonds_explicit, selfies, sanitize, all_hs_explicit, remove_bonddir, remove_chirality, randomize, add_start_and_stop, padding, padding_length, device.
Here are the problems:
Provided arg add_start_and_stop:True does not match the smiles_language value: False NOTE: smiles_language value takes preference!!
Provided arg padding:True does not match the smiles_language value: False NOTE: smiles_language value takes preference!!
Provided arg padding_length:500 does not match the smiles_language value: None NOTE: smiles_language value takes preference!!
To get rid of this, adapt the smiles_language *offline*, feed itready for intended usage, and adapt the constructor args to be identical with their equivalents in the language object`

## Steps to Reproduce the Problem

I was looking into code and couldn't find, where this Message get printed out.

It would be very helpful If you can help me with understanding the message and how I should preprocess my data.

Thanks a lot beforehand,
Cedric

**Comment by mcred** [comment]
Can you share your `titan run` command used to create your datasets? The message provided here isn't anything that titan would output, so I don't know where it's coming from.

**Comment by cirdeCyL** [comment]
Sure.

`python ./scripts/semifrozen_finetuning.py v1.2_data/uniform/Fold0/training.csv v1.2_data/uniform//Fold0/test.csv v1.2_data/tcr.csv v1.2_data/epitopes.smi public/trained_model v1.2_model/bugtest fold0 public/trained_model/finetune_params.json bimodal_mca`

**Comment by mcred** [comment]
I think you might have the wrong titan project. None of that is code or configuration for this project. The docs for this project are available here: https://titan-data.io/. If those are not the docs you are following, it's a different titan project.

**Comment by cirdeCyL** [comment]
Ja sry. i unfortunately got the wrong Titan project. I am sorry for your inconvenience. I'll close this ticket in my own embarassment
