### ISSUE TITLE
titan install not successful in Apple M1

### ISSUE THREAD

**Issue by sourceful-karlson** [titan-data/titan#276]
## Expected Behavior

Describe what should have happened.

titan install 

## Actual Behavior

Describe what actually happened.

titan install  not successful in Apple M1

## Steps to Reproduce the Problem

Describe in as much detail as possible how to reproduce the problem.

titan install 

Starting titan server docker containers | panic: 6b0afa1576ad0a1ab3b07ce59a8a407a5fb7700a68917f33078fad930fbc6212
docker: Error response from daemon: OCI runtime create failed: container_linux.go:380: starting container process caused: process_linux.go:545: container init caused: rootfs_linux.go:76: mounting "/lib" to rootfs at "/var/lib/titan-docker/system" caused: mkdir /var/lib/docker/overlay2/327567b41a1cef50c010ee06448d3f93c7ba653d0332e5c55473ffdbef0235c3/merged/var/lib/titan-docker: operation not permitted: unknown.

## Version

Indicate the relevant versions of components. This may include the Titan
package version, operating system version, or other components relevant to
the project.

## Additional Information

Add any additional logs or debugging information if appropriate.

**Comment by mcred** [comment]
Are you using gRPC Fuse for file sharing? This setting is usually active by default on newer docker desktop installations. Titan uses the legacy osxfs file sharing. Looks like the image link is broken, but this is mentioned in the [docs](https://titan-data.io/docs/version/0.5.4/lifecycle/docker.html#system-specific-setup).

**Comment by sourceful-karlson** [comment]
tks, I will check on this

**Comment by sourceful-karlson** [comment]
awesome, that works, really sorry for not reading the doc too much

**Comment by mcred** [comment]
No sweat! It's one line in the docs and the image link is currently broken. I almost missed while looking for it and I wrote it!
