### ISSUE TITLE
ability to delete local commits

### ISSUE THREAD

**Issue by eschrock** [titan-data/titan#32]
## Problem

Local commits take up storage, it would be nice to be able to clean up space.

## Solution

`titan-server` exposes an endpoint for deleting commits, we should hook that up somehow (`commit -D` or maybe a new subcommand?)

## Alternatives

Delete the whole repository.

**Comment by mcred** [comment]
What about a `titan delete` group where we could add items to be deleted, like commit. `titan delete commit -c GUID`?
