### ISSUE TITLE
sunec warning on linux

### ISSUE THREAD

**Issue by eschrock** [titan-data/titan#37]
Running 3.1.0 on CentOS:

[r2@localhost ~]$ titan clone s3://titan-data-demo/hello-world/postgres foo
WARNING: The sunec native library, required by the SunEC provider, could not be loaded. This library is usually shipped as part of the JDK and can be found under <JAVA_HOME>/jre/lib/<platform>/libsunec.so. It is loaded at run time via System.loadLibrary("sunec"), the first time services from SunEC are accessed. To use this provider's services the java.library.path system property needs to be set accordingly to point to a location that contains libsunec.so. Note that if java.library.path is not set it defaults to the current working directory.
Creating repository foo

**Comment by bigjazzsound** [comment]
I'm also experiencing the same issue on Fedora 30.
