### ISSUE TITLE
provide alternate image path for install

### ISSUE THREAD

**Issue by eschrock** [titan-data/titan#8]
## Problem

If a user doesn't have access to docker hub due to firewall issues, etc, they have no way of installing titan because the image path is hard-coded.

## Solution

Provide `titan install [-i image]` to specify an alternate image path. This would let them go through their own offline certification process to vet the titan images, host in a private registry, etc.

## Alternatives

I believe they can address this by manually pulling an image and tagging it as `titan:latest`, but it might be nice to have it as a first-class option.

**Comment by mcred** [comment]
Should the CLI still be in charge of the correct version? `-i myregistry:titan` vs `-i myregistry:titan:0.4.0`
