### ISSUE TITLE
push/pull doesn't report all information

### ISSUE THREAD

**Issue by eschrock** [titan-data/titan#87]
## Expected Behavior

```
$ titan push postgres
Pushing 4d8924cf9905462e9e02fd97b8ab4d15 to 'origin'
push operations are not supported for s3web provider
Push failed
```

## Actual Behavior

```
$ titan push postgres
PUSH 4d8924cf9905462e9e02fd97b8ab4d15 to origin RUNNING
Pushing 4d8924cf9905462e9e02fd97b8ab4d15 to 'origin'
PUSH 4d8924cf9905462e9e02fd97b8ab4d15 to origin FAILED
```

The issue is that we're keying off the operation state, not the last progress entry. So we get the initial status, check the operation, see it's failed, and break. But there are more progress entries to be consumed.

## Steps to Reproduce the Problem

Try to push to an s3web origin

## Version

0.3.4

**Comment by mcred** [comment]
I think this is a part of #26 and #9. In general, all of the progress tracking.
